#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10
ENV_FILE=".env.render.local"

require_value() {
  local name="$1" value="$2"
  if [[ -z "$value" ]]; then
    warn "$name cannot be empty. Re-run the wizard when the value is ready."
    exit 1
  fi
}

load_env_safely() {
  local key value
  while IFS='=' read -r key value; do
    [[ -z "$key" || "$key" == \#* ]] && continue
    export "$key=$value"
  done < "$ENV_FILE"
}

seed_owner() {
  if [[ ! -f "$ENV_FILE" ]]; then
    warn "$ENV_FILE is missing. Run the full deployment wizard first."
    exit 1
  fi
  say "This runs the one-time seed command locally against Neon. The password is never written to disk."
  ask OWNER_NAME "Owner display name:"
  ask OWNER_EMAIL "Owner email:"
  ask OWNER_PHONE "Owner phone (include country code):"
  ask_secret OWNER_PASSWORD "Owner password:"
  for pair in "OWNER_NAME:$OWNER_NAME" "OWNER_EMAIL:$OWNER_EMAIL" "OWNER_PHONE:$OWNER_PHONE" "OWNER_PASSWORD:$OWNER_PASSWORD"; do
    require_value "${pair%%:*}" "${pair#*:}"
  done
  if confirm "Create this production Owner now? This should be run only once."; then
    load_env_safely
    export OWNER_NAME OWNER_EMAIL OWNER_PHONE OWNER_PASSWORD
    GOCACHE="${TMPDIR:-/tmp}/mostlyvers-seed-cache" go run ./cmd/seed
  else
    SKIPPED+=("production Owner seed")
  fi
}

if [[ "${1:-}" == "--seed-owner-only" ]]; then
  TOTAL_STAGES=1
  banner "MOSTLYVERS · Create production Owner"
  stage "Create the initial Owner"
  seed_owner
  finish
  exit 0
fi

banner "MOSTLYVERS backend · Render deployment"

stage "Neon PostgreSQL"
say "Capture the pooled TLS connection string for the production database."
open_url "https://console.neon.tech/app/projects"
step "Open the project, click Connect, select Pooled connection, and copy the postgres:// URL."
ask_secret DATABASE_URL "Paste the pooled DATABASE_URL:"
require_value DATABASE_URL "$DATABASE_URL"
write_env DATABASE_URL "$DATABASE_URL"
chmod 600 "$ENV_FILE"

stage "Supabase private object storage"
say "Use the private bucket and server-side S3 credentials you created."
open_url "https://supabase.com/dashboard/projects"
step "Open the project, then Storage → Configuration → S3. Copy the direct storage endpoint and region."
ask STORAGE_ENDPOINT "S3 endpoint (https://PROJECT_REF.storage.supabase.co/storage/v1/s3):"
ask STORAGE_REGION "Project region (for example ap-south-1):"
ask STORAGE_BUCKET "Private bucket name:"
ask_secret STORAGE_ACCESS_KEY_ID "S3 Access Key ID:"
ask_secret STORAGE_SECRET_ACCESS_KEY "S3 Secret Access Key:"
for pair in \
  "STORAGE_ENDPOINT:$STORAGE_ENDPOINT" \
  "STORAGE_REGION:$STORAGE_REGION" \
  "STORAGE_BUCKET:$STORAGE_BUCKET" \
  "STORAGE_ACCESS_KEY_ID:$STORAGE_ACCESS_KEY_ID" \
  "STORAGE_SECRET_ACCESS_KEY:$STORAGE_SECRET_ACCESS_KEY"; do
  require_value "${pair%%:*}" "${pair#*:}"
done
write_env STORAGE_ENDPOINT "$STORAGE_ENDPOINT"
write_env STORAGE_REGION "$STORAGE_REGION"
write_env STORAGE_BUCKET "$STORAGE_BUCKET"
write_env STORAGE_PUBLIC_BUCKET "$STORAGE_BUCKET"
write_env STORAGE_ACCESS_KEY_ID "$STORAGE_ACCESS_KEY_ID"
write_env STORAGE_SECRET_ACCESS_KEY "$STORAGE_SECRET_ACCESS_KEY"
write_env STORAGE_SOFT_LIMIT_BYTES "891289600"
write_env STORAGE_HARD_LIMIT_BYTES "996147200"
write_env MAX_EPUB_UPLOAD_BYTES "52428800"

stage "Cloudinary images"
say "Cloudinary stores covers, author photos, and profile pictures only."
open_url "https://console.cloudinary.com/settings/api-keys"
step "Copy the cloud name, API key, and API secret from API Keys."
ask CLOUDINARY_CLOUD_NAME "Cloud name:"
ask_secret CLOUDINARY_API_KEY "API key:"
ask_secret CLOUDINARY_API_SECRET "API secret:"
require_value CLOUDINARY_CLOUD_NAME "$CLOUDINARY_CLOUD_NAME"
require_value CLOUDINARY_API_KEY "$CLOUDINARY_API_KEY"
require_value CLOUDINARY_API_SECRET "$CLOUDINARY_API_SECRET"
write_env CLOUDINARY_CLOUD_NAME "$CLOUDINARY_CLOUD_NAME"
write_env CLOUDINARY_API_KEY "$CLOUDINARY_API_KEY"
write_env CLOUDINARY_API_SECRET "$CLOUDINARY_API_SECRET"

stage "EmailJS transactional email"
say "EmailJS sends signup OTP and recovery messages through a connected personal Gmail account."
open_url "https://dashboard.emailjs.com/admin"
step "Connect Gmail, create the MOSTLYVERS template, then copy its service, template, and account keys."
ask EMAILJS_SERVICE_ID "EmailJS service ID:"
ask EMAILJS_TEMPLATE_ID "EmailJS template ID:"
ask EMAILJS_PUBLIC_KEY "EmailJS public key:"
ask_secret EMAILJS_PRIVATE_KEY "EmailJS private key (recommended for server-side requests):"
for pair in \
  "EMAILJS_SERVICE_ID:$EMAILJS_SERVICE_ID" \
  "EMAILJS_TEMPLATE_ID:$EMAILJS_TEMPLATE_ID" \
  "EMAILJS_PUBLIC_KEY:$EMAILJS_PUBLIC_KEY"; do
  require_value "${pair%%:*}" "${pair#*:}"
done
write_env EMAILJS_SERVICE_ID "$EMAILJS_SERVICE_ID"
write_env EMAILJS_TEMPLATE_ID "$EMAILJS_TEMPLATE_ID"
write_env EMAILJS_PUBLIC_KEY "$EMAILJS_PUBLIC_KEY"
write_env EMAILJS_PRIVATE_KEY "$EMAILJS_PRIVATE_KEY"

stage "Production origins and cryptographic secrets"
say "The admin origin must be an exact HTTPS origin, with no path or trailing slash."
say "If Cloudflare Pages is not deployed yet, enter https://bootstrap.invalid for the first Render deployment."
say "After Pages gives you its real URL, replace this value in Render and redeploy the backend."
ask ADMIN_ORIGIN "Cloudflare Pages origin, or https://bootstrap.invalid for bootstrapping:"
require_value ADMIN_ORIGIN "$ADMIN_ORIGIN"
if [[ "$ADMIN_ORIGIN" != https://* ]]; then
  warn "ADMIN_ORIGIN must start with https://"
  exit 1
fi
write_env ADMIN_ORIGIN "${ADMIN_ORIGIN%/}"
if [[ "$ADMIN_ORIGIN" == "https://bootstrap.invalid" ]]; then
  warn "Bootstrap origin selected. Admin login will remain blocked until ADMIN_ORIGIN is replaced in Render."
fi

generated=$(GOCACHE="${TMPDIR:-/tmp}/mostlyvers-keygen-cache" go run ./cmd/keygen)
for key in ACCESS_TOKEN_PRIVATE_KEY_BASE64 CONTENT_KEY_ENCRYPTION_KEY_BASE64 INTERNAL_JOB_TOKEN BACKUP_PASSPHRASE; do
  current=$(_existing "$key" || true)
  if [[ -z "$current" ]]; then
    current=$(printf '%s\n' "$generated" | grep -E "^${key}=" | cut -d= -f2-)
  fi
  write_env "$key" "$current"
done
write_env APP_ENV "production"
write_env BILLING_MODE "FREE_LAUNCH"
write_env EMAIL_PROVIDER "emailjs"
write_env EMAIL_OTP_REQUIRED "true"
write_env ADMIN_COOKIE_SECURE "true"
write_env PLAY_INTEGRITY_REQUIRED "false"
write_env ANDROID_PACKAGE_NAME "com.mostlyvers.app"
write_env READER_RESET_URL "mostlyvers://reset-password"
note "Play Integrity remains disabled only for initial testing. Enable it before Play Store release."

stage "Create the Render Blueprint"
say "Render will build the Dockerfile and prompt for every secret marked sync:false."
open_url "https://dashboard.render.com/blueprints"
step "Click New Blueprint and connect adarsh4567/mostlyvers-backend."
step "Use branch main and the root render.yaml, then click Deploy Blueprint."
step "For each requested variable, copy its value from $(pwd)/$ENV_FILE."
step "Do not add PORT or PUBLIC_BASE_URL; Render supplies the port and the app derives its Render URL."
pause "Press Enter after Render has accepted the Blueprint and started the deployment."

stage "Verify the deployed API"
step "Open the mostlyvers-api service and copy its https://…onrender.com URL."
ask API_ORIGIN "Render API origin (no /v1 suffix):"
require_value API_ORIGIN "$API_ORIGIN"
API_ORIGIN="${API_ORIGIN%/}"
if [[ "$API_ORIGIN" != https://* ]]; then
  warn "API_ORIGIN must start with https://"
  exit 1
fi
write_env API_ORIGIN "$API_ORIGIN"
write_env PUBLIC_BASE_URL "$API_ORIGIN"
say "Checking live, ready, and version endpoints. The first free-tier request can take about a minute."
curl --retry 5 --retry-delay 10 --retry-all-errors --max-time 180 --fail --silent --show-error "$API_ORIGIN/health/live"
printf '\n'
curl --retry 5 --retry-delay 10 --retry-all-errors --max-time 180 --fail --silent --show-error "$API_ORIGIN/health/ready"
printf '\n'
curl --retry 5 --retry-delay 10 --retry-all-errors --max-time 180 --fail --silent --show-error "$API_ORIGIN/version"
printf '\n'

stage "Create the initial Owner"
seed_owner

stage "GitHub deployment and job automation"
say "The wizard will store only workflow-required values in GitHub Actions secrets."
open_url "https://dashboard.render.com/"
step "Open mostlyvers-api → Settings → Deploy Hook, create/copy the hook URL."
ask_secret RENDER_DEPLOY_HOOK "Render deploy-hook URL:"
require_value RENDER_DEPLOY_HOOK "$RENDER_DEPLOY_HOOK"
load_env_safely
set_secret RENDER_DEPLOY_HOOK "$RENDER_DEPLOY_HOOK"
set_secret API_ORIGIN "$API_ORIGIN"
set_secret INTERNAL_JOB_TOKEN "$INTERNAL_JOB_TOKEN"
set_secret DATABASE_URL "$DATABASE_URL"
set_secret STORAGE_ENDPOINT "$STORAGE_ENDPOINT"
set_secret STORAGE_REGION "$STORAGE_REGION"
set_secret STORAGE_BUCKET "$STORAGE_BUCKET"
set_secret STORAGE_ACCESS_KEY_ID "$STORAGE_ACCESS_KEY_ID"
set_secret STORAGE_SECRET_ACCESS_KEY "$STORAGE_SECRET_ACCESS_KEY"
set_secret BACKUP_PASSPHRASE "$BACKUP_PASSPHRASE"

stage "Final backend smoke checks"
say "Confirm the service is healthy before connecting the admin dashboard and Android app."
step "In Render Logs, confirm migrations completed and the API is listening without configuration errors."
step "After Cloudflare Pages deploys, replace bootstrap.invalid with the exact https://PROJECT.pages.dev URL in Render → Environment → ADMIN_ORIGIN, then Save and deploy."
step "In Supabase Storage, keep the bucket private. Do not create a public read policy."
step "In EmailJS, confirm the Gmail service remains connected and the monthly request allowance is available."
step "Run the GitHub run-background-jobs workflow manually and confirm it succeeds."
open_url "https://github.com/adarsh4567/mostlyvers-backend/actions"
pause "Press Enter after checking the Render logs and GitHub workflow."

finish
warn "Keep $ENV_FILE private. Delete it only after Render and GitHub are configured and the Owner is seeded."
